#!/bin/sh

#cd /home/azureuser/WORKING/fin

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# remove surface and features
\rm -f constant/triSurface/fin.stl > /dev/null 2>&1
\rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
\rm -f constant/triSurface/fin.eMesh > /dev/null 2>&1

rm -rf 0 > /dev/null 2>&1

cleanCase

cd /home/azureuser/WORKING/fin/
